// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/visualization/__namespace__.js', ['visualization'], ['visualization.canvas.ManhattanPlot', 'visualization.canvas.ScatterPlot', 'visualization.svg.ManhattanPlot', 'visualization.svg.ScatterPlot'], false);
goog.addDependency('../../../../src/visualization/canvas/manhattan-plot.js', ['visualization.canvas.ManhattanPlot'], [], false);
goog.addDependency('../../../../src/visualization/canvas/scatter-plot.js', ['visualization.canvas.ScatterPlot'], [], false);
goog.addDependency('../../../../src/visualization/svg/manhattan-plot.js', ['visualization.svg.ManhattanPlot'], [], false);
goog.addDependency('../../../../src/visualization/svg/scatter-plot.js', ['visualization.svg.ScatterPlot'], [], false);
