// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/vs/ui/base.js', ['vs.ui'], [], false);
goog.addDependency('../../../../src/vs/ui/plugins/__namespace__.js', ['vs.ui.plugins'], ['vs.ui.plugins.canvas.ManhattanPlot', 'vs.ui.plugins.canvas.ScatterPlot', 'vs.ui.plugins.svg.Heatmap', 'vs.ui.plugins.svg.ManhattanPlot', 'vs.ui.plugins.svg.ScatterPlot'], false);
goog.addDependency('../../../../src/vs/ui/plugins/canvas/manhattan-plot.js', ['vs.ui.plugins.canvas.ManhattanPlot'], ['vs.ui'], false);
goog.addDependency('../../../../src/vs/ui/plugins/canvas/scatter-plot.js', ['vs.ui.plugins.canvas.ScatterPlot'], ['vs.ui'], false);
goog.addDependency('../../../../src/vs/ui/plugins/svg/binary-plot.js', ['vs.ui.plugins.svg.BinaryPlot'], ['vs.ui'], false);
goog.addDependency('../../../../src/vs/ui/plugins/svg/heatmap.js', ['vs.ui.plugins.svg.Heatmap'], ['vs.ui'], false);
goog.addDependency('../../../../src/vs/ui/plugins/svg/manhattan-plot.js', ['vs.ui.plugins.svg.ManhattanPlot'], ['vs.ui'], false);
goog.addDependency('../../../../src/vs/ui/plugins/svg/scatter-plot.js', ['vs.ui.plugins.svg.ScatterPlot'], ['vs.ui'], false);
